### ISSUE TITLE
add_tx_notify needs a timeout for giving up

### ISSUE THREAD

**Issue by chris-belcher** [JoinMarket-Org/joinmarket#118]
add_tx_notify() from BlockchainInterface needs some kind of timeout when it gives up waiting for confirmations. Then a yield generator can call sync_unspent() again to get back to normal and discard a tx that will never confirm.

**Comment by chris-belcher** [comment]
Of course there already is a timeout when using blockr.io
There would need to be another callback function invoked when the timeout is reached which the yield generator can used.

**Comment by tailsjoin** [comment]
Had another tumble session hung on me for some hours due to a failed push to blockr.

https://gist.github.com/anonymous/281738824147f807b82f

**Comment by chris-belcher** [comment]
That must be frustrating.
I've decoded the txhex (using [coinjumble](https://github.com/chris-belcher/coinjumble)) and I can't see anything wrong with it.

Did you manage to see any error message printed out? You could try broadcasting the tx (or I could do it) and see if it gets relayed. If so then we could try having the bot rebroadcast transactions again after the timeout. But if the tx fails every time then what do we do? I guess discard it and start a coinjoin from scratch?

**Comment by tailsjoin** [comment]
No error message, I copy/pasted from the terminal. 

In the past I have manually pushed these txs, even using blockrs api. So a second attempt might be all that's needed for most cases (should wait maybe 10 seconds and then reattempt). If that fails, then starting over would probably be the cleanest way to handle it.

I already spent those utxos, so that signed tx is useless now.

That was 6 of 18 on the session.
