### ISSUE TITLE
Infographic - "A 1st Glimpse on JoinMarket"

### ISSUE THREAD

**Issue by marcoagner** [JoinMarket-Org/joinmarket#244]
Hey!

I'm reading and getting comfortable with the project's code and plan to get my hands dirty soon...

It happens that I showed the project to a like-minded designer friend. She got excited about the project and wanted to create a first infographic about JoinMarket. She also wants to try some logo ideas soon.

Let us know what you think about the infographic and if there's some fixes/improvements so she can apply them.

![jm_infographic](https://cloud.githubusercontent.com/assets/5016303/10127657/0878ce88-657c-11e5-92e7-d726b872f633.png)

**Comment by CohibAA** [comment]
Awesome

**Comment by AdamISZ** [comment]
> Awesome

+1

"glimpse on" --> "glimpse at"

I like the blender :)

**Comment by chris-belcher** [comment]
This is great! Thanks for doing this.

It's totally awesome. There's only one or two things I'd change.

I wouldn't use the word anonymity, it has a negative feel to it. Instead use the words privacy and confidentiality or "making transactions in confidence".

You could also add a few words about scalability, since coinjoin can be used to combine transactions so that many economy transactions are in one bitcoin on-chain transaction. Probably nobody is using joinmarket like this now because miner fees are cheap so there's no reason to. But there is the script `patientsendpayment.py` that does this. And one day there could be a `patient-tumbler.py`.

A maker doesn't necessarily want to earn an income from their coins. A maker just means someone who is willing to wait, they could also be waiting for someone else to start the coinjoin using `patientsendpayment.py`. I originally thought users wouldn't ever use the words maker and taker but it seems it's caught on and everyone's comfortable with the idea.
Another benefit that maker's get is their bitcoins get mixed up(!) I saw someone offer orders for zero fee, presumably they were doing a very low cost tumble and didn't mind waiting.
When I didn't want to use the names maker/taker I would call people who run `yield-generator.py` investors or something like that. 'Takers' is replaced by 'people who want privacy now'

cyberguerilla is only one centralized IRC network. One day we'll have the bots connect to many different networks in case one goes down, bans us or something like that.

**Comment by tailsjoin** [comment]
I love it!

**Comment by marcoagner** [comment]
Great. 
Happy you liked it and thank you for the fixes and improvements proposed.

She's going to create a github account today so she can keep the discussion for herself without me as an intermediary. :)

**Comment by sofiab1** [comment]
Hi! I'm the one who created the graphic.
Thanks everyone for the feedback, I'm glad to help with this project. I'll take another look considering everything you all said and I'll upload the new version when I'm finished.
@chris-belcher, about the cyberguerilla network, I mentioned it because I was afraid that only saying "the pit" would be too vague. Do you (or anyone, of course) have a suggestion about whether I leave just "the pit" or I replace the cyberguerilla part with anything else more appropriate?

**Comment by tailsjoin** [comment]
>Do you (or anyone, of course) have a suggestion about whether I leave just "the pit" or I replace the cyberguerilla part with anything else more appropriate?

For now the statement on the graphic is factually correct, but may change in the future. IMO it should stay how it is until it becomes inaccurate.

**Comment by chris-belcher** [comment]
"the pit" name comes from this https://en.wikipedia.org/wiki/Open_outcry

I don't know if people find it confusing but "the meeting place on an irc channel" could be used instead?

We've been planning the multi-network irc for a while now, heres the issue https://github.com/chris-belcher/joinmarket/issues/116

**Comment by AdamISZ** [comment]
"the trading pit" would work (at least, a larger proportion of people would recognize the reference).

**Comment by sofiab1** [comment]
thanks!! I'll think about these options and I'll make the improvements then!

**Comment by francoisharris** [comment]
As a 'maker' what sort of income can you get from investing say 1BTC? How profitable would this be if I want to grow my bitcoin stash?

**Comment by JulianTosh** [comment]
only a few satoshi, plus free moxing at the moment. as more plugins to
wallets get developed, it may increase, but it will always be a race to
near zero margin.

- Sent from a superior 9.5 cubic inch Android mobile computing device.

**Comment by bhec39** [comment]
address, not adress.

**Comment by eragmus** [comment]
Beautiful infographic, @sofiab1.

**Comment by jonstern** [comment]
Beautiful

**Comment by ManfredKarrer** [comment]
@sofiab1 @marcoagner Congrats and thanks for supporting important projects! Good design is certainly in shortage in the Bitcoin world and great to get some help from you!

**Comment by marcoagner** [comment]
Thanks, @ManfredKarrer. I'm glad to support such important project in some way. But all I had to do for now was to present JoinMarket to @sofiab1 and say her design skills would be great around here... It's all her merits with the design work. :)

Btw, I suppose she's posting an updated infographic in a moment from now...

**Comment by sofiab1** [comment]
Thanks again everybody for the positive comments and critics. I'm posting a new version where I thought about the points and suggestions you made. Any new thoughts (or misspellings that you find XD), please, be welcome to share.
![jm_v2](https://cloud.githubusercontent.com/assets/14277752/10272910/c9c2e688-6afd-11e5-82f9-415eb5d63d43.png)

**Comment by sofiab1** [comment]
And.. I'm just posting the images here so it's easier for everybody to help me improving it. After we have a good version, I can easily provide the .ai (Illustrator file) together with the high resolution version on .png. 

I'd could use suggestions on how I can contribute in a way that the process doesn't depend just on my and anybody with the skills can contribute more easily later... Thanks!

**Comment by chris-belcher** [comment]
Great work @sofiab1 
It all looks good to me. Unless others spot something in the next few days, we could start spreading this around.

**Comment by AdamISZ** [comment]
@sofiab1 @marcoagner Perhaps post this on reddit r/joinmarket (and maybe r/Bitcoin) now? Maybe things like twitter too?

**Comment by chris-belcher** [comment]
Congratulations for being the highest thread on /r/bitcoin

**Comment by dooglus** [comment]
https://www.reddit.com/r/Bitcoin/comments/3od0pv/a_1st_glimpse_on_joinmarket_infographic/ is the URL for reference.

I have a small nit to pick:

I personally think it would look better with "First" in the title. Or maybe "1st" is OK if the "1" looked like a digit rather than a capital "i", or was closer to the "st". I misread it as "A I st" and took too long to realise what it was trying to say.

**Comment by sofiab1** [comment]
@adamISZ, thanks for the suggestion, it already went to reddit.

@chris-belcher, thanks, I'm glad I opened some space for people to ask more about the project.

@dooglus, I agree with you. The typeface I used has this strange "1" that looks like an "I". I'll take a look at it when I can. 

For this and other changes... my computer is kind of dead and I'm not sure how much time will be until I have it up and running. But I can upload the .ai file before I fix it if anyone wants to make changes right now.

**Comment by AdamISZ** [comment]
@sofiab1  @marcoagner 

I'm building a GUI tool and need an icon. I think the blender from the infographic could be good for that. Could I get your permission and/or help to get a *.ico file for that? Thanks.

**Comment by sofiab1** [comment]
Hi, @AdamISZ. You can use the blender, there's no problem at all.
My quick solution for you here will be uploading the blender in the .ai format. Can you work with that?
[blender.ai.zip](https://github.com/JoinMarket-Org/joinmarket/files/107515/blender.ai.zip)

**Comment by sofiab1** [comment]
I'll also upload the whole infographic in the .ai format, in case anyone in the project wants to make changes in it.
[JM.ai.zip](https://github.com/JoinMarket-Org/joinmarket/files/107518/JM.ai.zip)

**Comment by AdamISZ** [comment]
@sofiab1 thanks muchly, a bit overwhelmed getting the gui ready now, I will pick this up, it's on the TODO list
