### ISSUE TITLE
Orderbook bomb [DoS]

### ISSUE THREAD

**Issue by dcousens** [JoinMarket-Org/joinmarket#298]
```
!orderbook!orderbook!orderbook!orderbook!orderbook!orderbook!orderbook!orderbook!orderbook!orderbook!orderbook!orderbook!orderbook!orderbook!orderbook!orderbook!orderbook!orderbook!orderbook!orderbook!orderbook!orderbook!orderbook!orderbook!orderbook!orderbook!orderbook!orderbook!orderbook!orderbook!orderbook!orderbook!orderbook!orderbook!orderbook!orderbook!orderbook!orderbook!orderbook!orderbook!orderbook!orderbook
```

1 message for me, `m * n` responses from others.

We should probably penalize users who do things like this?

**Comment by dcousens** [comment]
Perhaps we could [at least] rate limit `!orderbook` commands, given their broadcast nature.
We should probably also penalize users if a command is unexpected **and** repeated.

**Comment by AdamISZ** [comment]
See #361 - this addresses this issue, BUT only in the very limited sense as mentioned in #343 , namely, "prevent crash/DOS in case of someone's bug". Attempting to address this in terms of punishing bad behaving counteparties is in the scope of 0.2.0 according to the taxonomy of that issue, because it doesn't make too much sense as long as counterparties are almost entirely 'weightless', as they are today.
