### ISSUE TITLE
Default tumbler settings can produce endless irc disconnect loop.

### ISSUE THREAD

**Issue by tailsjoin** [JoinMarket-Org/joinmarket#301]
-N MAKERCOUNTRANGE, --makercountrange=MAKERCOUNTRANGE
                            Input the mean and spread of number of makers to use.
                            e.g. 3 1.5 will be a normal distribution with mean 3
                            and standard deveation 1.5 inclusive, default=3 1.5

It appears that this would produce a maximum of 5 makers, but I just ran a tumbler session and I had an attempt at 7 makers that just ended up in an infinite loop of disconnecting from irc and then reattempting the tx.

    {'liquiditywait': 60, 'addrcount': 3, 'minmakercount': 2, 'amountpower': 100.0, 'txcountparams': (4, 1), 'mixdepthcount': 4, 'waittime': 20, 'txfee': 10000, 'mincjamount': 100000, 'mixdepthsrc': 0, 'makercountrange': (3, 1.5), 'maxcjfee': (0.01, 10000), 'donateamount': 0, 'timelambda': 30, 'mintxcount': 1}    
    [2015/11/01 04:16:11] tumbler transaction list
    [{'srcmixdepth': 0,
      'tx': [{'amount_fraction': 0.2032669238683784,
              'destination': 'internal',
              'makercount': 2,
              'wait': 33.41},
             {'amount_fraction': 0.7967330761316216,
              'destination': 'internal',
              'makercount': 2,
              'wait': 3.01}]},
     {'srcmixdepth': 1,
      'tx': [{'amount_fraction': 0.595081156677217,
              'destination': 'internal',
              'makercount': 7,
              'wait': 16.4},
             {'amount_fraction': 0.4049188433227831,
              'destination': '[redacted]',
              'makercount': 2,
              'wait': 14.84}]},...

**Comment by chris-belcher** [comment]
A normal distribution can produce any output in theory. The shape of the probability distribution looks like this https://en.wikipedia.org/wiki/Normal_distribution#/media/File:Empirical_Rule.PNG In the JoinMarket tumbler, the maker count has a floor at N=2

So the question is why does N=7 makers result in your bot crashing. The answer is probably that the IRC server killed it due to flood, so issue #31 would fix this.

Part of the reason for calculating everything in the beginning and printing it is so the user can say no to these particular random parameters and try again. So as a workaround I'd say type 'n' if makercount=7 again.

**Comment by tailsjoin** [comment]
>So the question is why does N=7 makers result in your bot crashing. The answer is probably that the IRC server killed it due to flood, so issue #31 would fix this.

Yes that's why the kick.

**Comment by AdamISZ** [comment]
If the hypothesis is correct, then should be addressed by #366. Closing.
