### ISSUE TITLE
yield-generator-basic Crash

### ISSUE THREAD

**Issue by Onefox** [JoinMarket-Org/joinmarket#523]
Here is the debug log from last night.
Before that the generator worked fine for several hours and joins after a restart its working again.

http://pastebin.com/WLuLs2BM

**Comment by chris-belcher** [comment]
could you use this file on the entire log and then post it https://github.com/JoinMarket-Org/joinmarket/blob/master/logs/scrub-log.py

**Comment by Onefox** [comment]
Sure here you go:
http://pastebin.com/kDJTC9zJ

**Comment by chris-belcher** [comment]
Thanks for the report.

Looks like what happened is one of the UTXOs that yield-gen thought it had was actually not real. It went to recalculate which UTXOs it should use to fulfill the order but found there was now not enough bitcoins. This wasn't expected so it crashed.

> TIMESTAMP_0000000000420 [MainThread  ] [DEBUG]  mix depths that have enough = []

The way to fix this is somewhere around this line https://github.com/JoinMarket-Org/joinmarket/blob/087921b50beb93faa8e9125611b6cde7d12d4a16/yield-generator-basic.py#L107

check if len(filtered_mix_balance) == 0 and if it is then return None, None, None.

Tagging this as Easy / Quick to fix because it is.

**Comment by Onefox** [comment]
Just one more over here:
http://pastebin.com/SQAvvQeC

Also the oder is not being update in the oderbook after a trade could that be?

**Comment by AdamISZ** [comment]
This has been fixed in develop: https://github.com/JoinMarket-Org/joinmarket/commit/f9fd64f0d2d1ac8d16bf26425607b75443a7208c
