### ISSUE TITLE
Python wallet-tool.py failed to display addresses, generates an error.

### ISSUE THREAD

**Issue by jamesphillipturpin** [JoinMarket-Org/joinmarket#530]
Ran on Windows 8.1 machine. Screen capture attached. There is the Command Prompt at top (for context) and the resulting Python shell at bottom.
![windows8 1](https://cloud.githubusercontent.com/assets/4017015/15451509/35c1181e-1f7b-11e6-8850-13f599d0e254.png)

I will have to study this quite a but to get up to speed and figure out the problem myself, so I thought I'd post this in case somebody else knows trivially what I'm doing wrong.

**Comment by chris-belcher** [comment]
You have an old version of python I think. I remember getting this once on Linux, it happens because the SSL module are out of date. One way to fix it which I dont recommend is to change all 'https' to 'http' inside blockchaininterface.py, however that means any wiretapper can see all your addresses (instead of with https where only blockr.io can see your address)

**Comment by AdamISZ** [comment]
I don't know how universal it is, but there's an edit I put together for Windows to fix this error connecting to blockr. At some point I was going to make a PR to put this in with a `platform` check so it was just for Windows (maybe?). The root cause seemed to be that the blockr website only accepts TLS1.2 connections, but the default setup doesn't use TLS1.2; maybe it was TLS1.0.

Sorry I know this is crappy as a solution, but I thought better to braindump it here than not.

Replace [this](https://github.com/JoinMarket-Org/joinmarket/blob/master/bitcoin/bci.py#L1-L22) with:

```
#!/usr/bin/python
import json, re
import random
import sys
'''try:
    from urllib.request import build_opener
except:
    from urllib2 import build_opener
'''
import ssl
import urllib2
 
# Makes a request to a given URL (first arg) and optional params (second arg)
def make_request(*args):
    #opener = build_opener()
    ctx = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)
    sh = urllib2.HTTPSHandler(debuglevel=0, context=ctx)
    opener = urllib2.build_opener(sh)
    opener.addheaders = [('User-agent',
                          'Mozilla/5.0' + str(random.randrange(1000000)))]
    try:
        return opener.open(*args).read().strip()
    except Exception as e:
        try:
            p = e.read().strip()
        except:
            p = e
        raise Exception(p)
```

**Comment by jamesphillipturpin** [comment]
Ah, that makes sense. I had Python 2.7.3 rather than 2.7.11. I already had
a backup for Python, so I just installed over the local copy and that fixed
it. Aside from a broken shortcut to IDLE (Python GUI), easily fixed, there
doesn't seem to be any negative ramifications - All my programs for Python
2.7.3 still run in Python 2.7.11.
On May 21, 2016 7:19 PM, "chris-belcher" <notifications@github.com> wrote:

You have an old version of python I think. I remember getting this once on
Linux, it happens because the SSL module are out of date. One way to fix it
which I dont recommend is to change all 'https' to 'http' inside
blockchaininterface.py, however that means any wiretapper can see all your
addresses (instead of with https where only blockr.io can see your address)

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/JoinMarket-Org/joinmarket/issues/530#issuecomment-220810586>

**Comment by AdamISZ** [comment]
Hmm, yes, seems quite likely that the upgrade to 2.7.11 fixes it without any code changes. Good news if so.
