### ISSUE TITLE
Use Tor stream isolation

### ISSUE THREAD

**Issue by raedah** [JoinMarket-Org/joinmarket#543]
The current configuration is just for JM to use the default circuit that all of the users other tor traffic is traveling over. JM should be using the tor stream isolation feature to create a distinct connection for JM to use so that there wont be correlation with other applications the user is using over tor.

**Comment by raedah** [comment]
https://www.torproject.org/docs/tor-manual.html.en
"IsolateSOCKSAuth - Don’t share circuits with streams for which different SOCKS authentication was provided. (On by default)"

What are we currently using for SOCKS authentication? Nothing? If it were to be randomized, that should create a new circuit. 

https://github.com/JoinMarket-Org/joinmarket/blob/master/joinmarket/irc.py#L628-L630

This should have worked.

                    """
                    setdefaultproxy(PROXY_TYPE_SOCKS5,
                        self.socks5_host, self.socks5_port,
                        True)
                    """
                    setdefaultproxy(proxytype=PROXY_TYPE_SOCKS5,
                        addr=self.socks5_host,
                        port=self.socks5_port,
                        rdns=True,
                        username=''.join(random.choice(string.lowercase) for i in range(8)),
                        password=''.join(random.choice(string.lowercase) for i in range(8)))

but all I am getting is

  File "/home/x/run/joinmarket/joinmarket/irc.py", line 646, in run
    self.sock.connect(self.serverport)
  File "/home/x/run/joinmarket/joinmarket/socks.py", line 391, in connect
    self.__negotiatesocks5(destpair[0], destpair[1])
  File "/home/x/run/joinmarket/joinmarket/socks.py", line 210, in __negotiatesocks5
    chr(len(self.proxy[5])) + self.__proxy[5])
AttributeError: 'socksocket' object has no attribute 'proxy'

**Comment by chris-belcher** [comment]
Yes,
I've put medium difficulty for now because I don't know how hard or easy it is.

**Comment by raedah** [comment]
Looks like the error is here, https://github.com/JoinMarket-Org/joinmarket/blob/master/joinmarket/socks.py#L209-L210

File "/home/joinmarket/joinmarket/socks.py", line 210, in __negotiatesocks5

AttributeError: 'socksocket' object has no attribute 'proxy'

So im just assuming that socks5 code is broken where user/pass auth is performed.

**Comment by chris-belcher** [comment]
Looks like it. Someone else found that socks5.py file from stack exchange I think (I had also used it previously for coinjumble) and it's had stuff fixed in it.
So yes just fix it and test. Probably change proxy to __proxy

**Comment by chris-belcher** [comment]
So is the socks5 auth used as some kind of random seed to build the tor circuit ?

**Comment by raedah** [comment]
https://gitweb.torproject.org/torspec.git/tree/socks-extensions.txt

  - The "NO AUTHENTICATION REQUIRED" (SOCKS5) authentication method [00] is
    supported; and as of Tor 0.2.3.2-alpha, the "USERNAME/PASSWORD" (SOCKS5)
    authentication method [02] is supported too, and used as a method to
    implement stream isolation. As an extension to support some broken clients,
    we allow clients to pass "USERNAME/PASSWORD" authentication to us even if
    no authentication was selected.

**Comment by AlexCato** [comment]
I've played around with this a bit, changing proxy[5] to __proxy[5] in that line fixes the crash indeed: https://github.com/JoinMarket-Org/joinmarket/blob/master/joinmarket/socks.py#L210 

I then used the randomized username and password as suggested by raedah.

This isolates multiple connections to the IRC server only if the clearnet IP adress of the server is used over the TOR proxy.
If the hidden irc service is configured, multiple streams are **not isolated**.

According to this [message on the tor mailing list](https://lists.torproject.org/pipermail/tor-talk/2012-September/025446.html), streams to **different** hidden services are isolated by default. I could not find how to isolate multiple streams to the **same** hidden service...

**Comment by nopara73** [comment]
I've just encountered this old issue, I thought I leave some of my thoughts here.

## Quick Recap

Tor uses username/passwd SOCKS5 authentication to isolate streams. This is not intuitive, but can work with that.

## New TCP Connection

One needs to create a new SOCKS5 over TCP connection to the Tor Control Port every time with different username/password authentication for new stream is to be isolated.

@AlexCato 
> According to this message on the tor mailing list, streams to different hidden services are isolated by default. I could not find how to isolate multiple streams to the same hidden service...

Do you mean SOCKS5 connections to the same hiddenservice won't get a new stream, even if a new TCP connection with different user/password authentication?

## Stream Isolation Not Enough?

@EthanHeilman talked about DNS fingerprinting back then. Maybe the `NEWNYM` control port request tackles it:

https://tor.stackexchange.com/questions/9853/what-happens-with-tcp-connections-on-signal-newnym
`NEWNYM` marks any previously used (dirty) circuits as unusable, so that subsequent connections will not use them, clears the client-side DNS cache, as mentioned in the spec (any mapping between address and IP) and clears the state of the rendezvous client (hidden services) to avoid possible links between the old and new nym because of the new nym starting with the end state of the old nym.

## Sidenote

Lol, it's almost midnight, new years eve here.

**Comment by nopara73** [comment]
@AlexCato 
In the meantime I implemented the Tor Socks5 protocol from scratch and attempted to the streamisolation.

### Conclusion:
TCP connection to the same server with uname/pwd authentication stream isolation WORKS.    

### Method 

To get my IP, I used `api.ipify.org:80`, because I couldn't find any onion to check, but I'm fairly positive it works the same way.  
The query was: `GET / HTTP/1.1\r\nHost:api.ipify.org\r\n\r\n`

### Not perfect

Without stream isolation, the IPs were the same. Sometimes it got a new IP 2/10.  
With stream isolation (sync code), the IPs were different 10/10. 
However when I concurrently requested TCP connections, stream isolation was not perfect. 8-9/10.  

So that's something to pay attention.
