### ISSUE TITLE
yield generators need a ignored_takers list

### ISSUE THREAD

**Issue by raedah** [JoinMarket-Org/joinmarket#579]
Would work like the tumblers  ignored_makers  does. Use to avoid spammers.

**Comment by AdamISZ** [comment]
Spammers can and do change identity all the time. Of course, makers can do the same, but the utility is real because (a) the maker may simply be unresponsive not malicious and (b) they generally operate passively not rejoining messaging all the time. I think on balance this isn't too helpful, *until* we implement some kind of anti-DOS/spam/snoop functionality (e.g. binding to utxos)

**Comment by raedah** [comment]
makes sense
