### ISSUE TITLE
"[DEBUG]  importing 46540 addresses into account joinmarket-wallet-xxxxxxx"

### ISSUE THREAD

**Issue by HamishMacEwan** [JoinMarket-Org/joinmarket#611]
I didn't leave that to complete.  

With the last version I was getting reports per 1000 and that seemed to be nearer 9000 than the amount above.

Is that safe?

Any other information happily supplied.

Hamish.

**Comment by AdamISZ** [comment]
When you say "last version" I don't suppose you know which commit you were running off? I'm guessing it was the last master, before the changes were made to try to automatically sync all necessary addresses at once, in either 1 or two runs, rather than the many people that reported having to run many, many times and in some cases getting stuck in an infinite sync loop.

The whole situation has been terribly difficult due to the relentless request-drop cycle of the spying actor. I suspect a fair number of people were not aware that they were getting maybe hundreds of requests per day, because they left it running in the background. Hopefully we can do what is necessary to get you back to a state that is workable. Can you report the contents of your index_cache fields in the wallet.json (it's just an array of wallet indices)?

**Comment by K1773R** [comment]
i had that too when upgrading to 0.2.
it took several hours, mainly because there is only 1 rpc thread feeding bitcoind.

**Comment by AdamISZ** [comment]
I'm investigating this: https://www.reddit.com/r/joinmarket/comments/4x95cl/whats_up_with_joinmarket_activity_the_past_few/d6z19rv .

If someone says they have this problem when upgrading to 0.2 it's hard to know exactly what's going on, because there were changes designed to improve sync, that I alluded to above, that happened about 3 months back, but on develop and not in 0.1.4, and also there is the spying behaviour and the question of how long it was since you last updated, how many transactions you've been having etc.

But on another level I'd like to look for an overall better model for syncing, the above link *might* be a good starting point.

Anyway please do continue with info @HamishMacEwan , also feel free to contact on IRC if it helps.

**Comment by HamishMacEwan** [comment]
Thanks for the responses.  My concern was for the size of my Bitcoin Core wallet.  All this talk of "importing 46540 addresses into account" had me concerned that some kind of duplication was occurring or worse.  I admit I had the previous version running while I was doing what I hoped would be isolated testing, eg. 

`python wallet-tool.py wallet.json summary`

As per request:

`"index_cache": [[255, 10032], [148, 12836], [185, 9783], [120, 7508], [124, 5654]]`
And yes, that does seem to suggest the import isn't awry...

As to the previous version, the best I can do there is offer this best guess at what might answer the question:
```
~/bin/joinmarket-master$ git status -b
HEAD detached from v0.1.4
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    wallets/.gitignore

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	bugreport.txt
	coldwalletstodo.txt
	logs/yigen-statement-wallet.csv
	logs/yigen-statement.csv
	secp256k1Install.txt
	secp256k1Install2.txt
	wallets

no changes added to commit (use "git add" and/or "git commit -a")
```

> As to this, I suspect you're referring to the output from listtransactions

I think you are right there.

**Comment by AdamISZ** [comment]
@HamishMacEwan I'm in the process of putting together a PR that should allow a (much) faster sync for existing wallets on existing Core. When it's ready I'll give you instructions on how to test it without affecting your current setup.

Re: doing a sync with another version running on the same wallet; obviously one doesn't want to do that (to avoid confusion), but unless I missed something, as long as it's in an isolated location (so the index_cache doesn't get overwritten or something), there's no actual danger in that.

**Comment by AdamISZ** [comment]
@HamishMacEwan see #612 (second comment has test instructions), let me know if you can, thanks.

**Comment by HamishMacEwan** [comment]
Look forward to that.   At present I've run the 0.2.1 version yg-pe.py and while it had no apparent problems, no customers either...

I made the minimum changes to joinmarket.cfg, but perhaps I've got more tuning to do...

**Comment by AdamISZ** [comment]
@HamishMacEwan did you try to follow the instructions in the link? I've also asked people to try it in IRC, no takers so far. I can't merge it without at least a couple of people sanity checking it, plus I'm very keen to know how much faster it is with a very large wallet.

**Comment by HamishMacEwan** [comment]
I will Adam, but it was a bit late when I saw your suggestion and I will need all my wits about me for that experiment, despite your excellent instructions.

Should have a result in a couple of hours, other things imposing themselves...
