### ISSUE TITLE
Maker required to know private key for coinjoin address

### ISSUE THREAD

**Issue by chris-belcher** [JoinMarket-Org/joinmarket#88]
To authenticate the end-to-end encryption, the maker send the pubkey of the coinjoin address.

That's bad because the maker has to know the private key, so patientsendpayment.py cannot do that. It also means the coinjoin address cant be a p2sh address.

Maker should use one of the inputs, same as the taker does.

This is a protocol change so would be incompatible with the older bots.

**Comment by AdamISZ** [comment]
Thought about it, and ACK.
Looking at the code now.

**Comment by AdamISZ** [comment]
Working through it, I see the need to change the !ioauth: message from 

    !ioauth utxo coinjoin_pubkey change_addr btc_sig

to

    !ioauth utxo input_pubkey coinjoin_addr change_addr btc_sig

since the input_pubkey cannot be recovered otherwise. However, the effect will only be to add about 32 bytes to the message (note: addresses take about 40ish bytes over the wire b64encoded, whereas pubkeys take more like 90), which seems fine I guess.

**Comment by AdamISZ** [comment]
Addressed by 0.2.0 release.
